networks:
  internal_network:
    driver: bridge

services:
  healthbot:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "python3 -m src.db.init_db && python3 -m src.main"
    env_file:
      - .env.prod
    volumes:
      - bot_logs:/var/www/service-healthbot/src/logs
    restart: on-failure
    networks:
      - internal_network
    
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - internal_network

volumes:
  bot_logs: